import { NextRequest, NextResponse } from "next/server";

const ADS: Record<string, object[]> = {
  as_001_1: [
    {
      id: "ad_001_1_a",
      adsetId: "as_001_1",
      name: "Samsonite Lite-Box Summer Escape – Video 15s",
      format: "video",
      spend: 9200,
      revenue: 51520,
      roas: 5.60,
      impressions: 278000,
      clicks: 8618,
      ctr: 3.10,
      conversions: 258,
      creative: {
        headline: "Escape This Summer with Samsonite",
        body: "Lightweight, durable, and stylish — the Samsonite Lite-Box is your perfect travel companion. Shop now and get free delivery across Egypt.",
        cta: "Shop Now",
        imageUrl: "https://placehold.co/1200x628/1a1a2e/ffffff?text=Samsonite+Lite-Box+Summer",
      },
    },
    {
      id: "ad_001_1_b",
      adsetId: "as_001_1",
      name: "Samsonite Cosmolite – Carousel 3 Products",
      format: "carousel",
      spend: 7000,
      revenue: 36770,
      roas: 5.25,
      impressions: 202000,
      clicks: 5782,
      ctr: 2.86,
      conversions: 188,
      creative: {
        headline: "Pack More. Weigh Less.",
        body: "Explore the Cosmolite collection — the world's lightest hard-shell suitcase, now available in Egypt. Perfect for business and leisure travel.",
        cta: "Explore Collection",
        imageUrl: "https://placehold.co/1200x628/0f3460/ffffff?text=Samsonite+Cosmolite+Carousel",
      },
    },
  ],
  as_001_2: [
    {
      id: "ad_001_2_a",
      adsetId: "as_001_2",
      name: "Family Travel – Static Image",
      format: "image",
      spend: 6800,
      revenue: 35020,
      roas: 5.15,
      impressions: 210000,
      clicks: 5880,
      ctr: 2.80,
      conversions: 188,
      creative: {
        headline: "Family Adventures Start Here",
        body: "From Alexandria beaches to Hurghada resorts — pack for the whole family with Samsonite. Free shipping on orders over EGP 2,000.",
        cta: "Shop Family Sets",
        imageUrl: "https://placehold.co/1200x628/16213e/ffffff?text=Samsonite+Family+Travel",
      },
    },
    {
      id: "ad_001_2_b",
      adsetId: "as_001_2",
      name: "Alexandria Promo – Video 30s",
      format: "video",
      spend: 5600,
      revenue: 25896,
      roas: 4.62,
      impressions: 160000,
      clicks: 4480,
      ctr: 2.80,
      conversions: 140,
      creative: {
        headline: "Alexandria to Anywhere — Samsonite",
        body: "Your journey begins with the right luggage. Discover Samsonite at our Alexandria store or order online with next-day delivery.",
        cta: "Find a Store",
        imageUrl: "https://placehold.co/1200x628/0d1b2a/ffffff?text=Samsonite+Alexandria",
      },
    },
  ],
  as_001_3: [
    {
      id: "ad_001_3_a",
      adsetId: "as_001_3",
      name: "Lookalike – Cosmolite Hero Image",
      format: "image",
      spend: 5900,
      revenue: 31802,
      roas: 5.39,
      impressions: 172000,
      clicks: 4988,
      ctr: 2.90,
      conversions: 152,
      creative: {
        headline: "Trusted by Travelers Worldwide",
        body: "Over 100 years of luggage excellence. The Samsonite Cosmolite is the choice of frequent flyers — now ships free within Egypt.",
        cta: "Buy Now",
        imageUrl: "https://placehold.co/1200x628/1b2a3b/ffffff?text=Samsonite+Cosmolite+Hero",
      },
    },
    {
      id: "ad_001_3_b",
      adsetId: "as_001_3",
      name: "Lookalike – Video Testimonial",
      format: "video",
      spend: 3900,
      revenue: 18668,
      roas: 4.79,
      impressions: 112000,
      clicks: 3248,
      ctr: 2.90,
      conversions: 96,
      creative: {
        headline: "Why Egyptians Choose Samsonite",
        body: "Real customers share their travel experiences with Samsonite. Join thousands of happy travelers across Egypt.",
        cta: "Watch & Shop",
        imageUrl: "https://placehold.co/1200x628/1c2e42/ffffff?text=Samsonite+Testimonial+Video",
      },
    },
  ],
  as_001_4: [
    {
      id: "ad_001_4_a",
      adsetId: "as_001_4",
      name: "Retargeting – Dynamic Product Ad",
      format: "carousel",
      spend: 2800,
      revenue: 12852,
      roas: 4.59,
      impressions: 96000,
      clicks: 2544,
      ctr: 2.65,
      conversions: 78,
      creative: {
        headline: "You Left Something Behind 👀",
        body: "Your Samsonite is still waiting for you. Complete your purchase today and enjoy free delivery anywhere in Egypt.",
        cta: "Complete Purchase",
        imageUrl: "https://placehold.co/1200x628/2c3e50/ffffff?text=Samsonite+Retargeting+DPA",
      },
    },
    {
      id: "ad_001_4_b",
      adsetId: "as_001_4",
      name: "Retargeting – Urgency Static",
      format: "image",
      spend: 1600,
      revenue: 6728,
      roas: 4.21,
      impressions: 54000,
      clicks: 1406,
      ctr: 2.60,
      conversions: 42,
      creative: {
        headline: "Limited Stock – Don't Miss Out!",
        body: "The item you viewed is almost sold out. Order now before it's gone. Free shipping within Egypt.",
        cta: "Order Now",
        imageUrl: "https://placehold.co/1200x628/34495e/ffffff?text=Samsonite+Urgency+Ad",
      },
    },
  ],
  as_002_1: [
    {
      id: "ad_002_1_a",
      adsetId: "as_002_1",
      name: "AT Back to School – Carousel Kids Bags",
      format: "carousel",
      spend: 8400,
      revenue: 47040,
      roas: 5.60,
      impressions: 252000,
      clicks: 8064,
      ctr: 3.20,
      conversions: 248,
      creative: {
        headline: "Ready for School? American Tourister Has You Covered",
        body: "Colorful, durable backpacks and trolleys for every student. Starting from EGP 850. Free delivery for back-to-school orders.",
        cta: "Shop School Bags",
        imageUrl: "https://placehold.co/1200x628/e74c3c/ffffff?text=AT+Back+to+School+Carousel",
      },
    },
    {
      id: "ad_002_1_b",
      adsetId: "as_002_1",
      name: "AT Back to School – Video 20s",
      format: "video",
      spend: 5600,
      revenue: 29260,
      roas: 5.23,
      impressions: 168000,
      clicks: 5376,
      ctr: 3.20,
      conversions: 160,
      creative: {
        headline: "The Perfect School Companion",
        body: "American Tourister school collection — built tough, loved by kids. Shop the full range online with fast delivery across Egypt.",
        cta: "View Collection",
        imageUrl: "https://placehold.co/1200x628/c0392b/ffffff?text=AT+School+Video",
      },
    },
  ],
  as_002_2: [
    {
      id: "ad_002_2_a",
      adsetId: "as_002_2",
      name: "AT Students – Funky Image",
      format: "image",
      spend: 7200,
      revenue: 36000,
      roas: 5.00,
      impressions: 230400,
      clicks: 6912,
      ctr: 3.00,
      conversions: 202,
      creative: {
        headline: "Show Your Style, Carry Your World",
        body: "American Tourister's bold designs match your campus energy. Lightweight carry-ons from EGP 1,200. Free shipping to your dorm.",
        cta: "Shop Now",
        imageUrl: "https://placehold.co/1200x628/8e44ad/ffffff?text=AT+Students+Style",
      },
    },
    {
      id: "ad_002_2_b",
      adsetId: "as_002_2",
      name: "AT Students – Reels Video",
      format: "video",
      spend: 3800,
      revenue: 19000,
      roas: 5.00,
      impressions: 119600,
      clicks: 3588,
      ctr: 3.00,
      conversions: 106,
      creative: {
        headline: "Pack It All In",
        body: "American Tourister's spacious designs mean you never have to choose what to bring. Perfect for study trips and university life.",
        cta: "Explore Bags",
        imageUrl: "https://placehold.co/1200x628/6c3483/ffffff?text=AT+Students+Reels",
      },
    },
  ],
  as_007_1: [
    {
      id: "ad_007_1_a",
      adsetId: "as_007_1",
      name: "TikTok Unboxing – Samsonite Lite-Box",
      format: "video",
      spend: 3200,
      revenue: 6880,
      roas: 2.15,
      impressions: 510000,
      clicks: 5100,
      ctr: 1.00,
      conversions: 48,
      creative: {
        headline: "Unboxing the Samsonite Lite-Box ✈️",
        body: "Watch us unbox the lightest hardshell suitcase ever. Available now in Egypt!",
        cta: "Shop Link in Bio",
        imageUrl: "https://placehold.co/1080x1920/000000/ffffff?text=TikTok+Unboxing+Video",
      },
    },
    {
      id: "ad_007_1_b",
      adsetId: "as_007_1",
      name: "TikTok Pack With Me – Samsonite",
      format: "video",
      spend: 2000,
      revenue: 4040,
      roas: 2.02,
      impressions: 310000,
      clicks: 3100,
      ctr: 1.00,
      conversions: 30,
      creative: {
        headline: "Pack With Me for Sharm El-Sheikh 🌊",
        body: "Fitting everything in my Samsonite carry-on! Link in bio to shop. #Travel #Samsonite #Egypt",
        cta: "Shop Now",
        imageUrl: "https://placehold.co/1080x1920/111111/ffffff?text=TikTok+Pack+With+Me",
      },
    },
  ],
  as_009_1: [
    {
      id: "ad_009_1_a",
      adsetId: "as_009_1",
      name: "Cart Abandonment – 10% Off Offer",
      format: "image",
      spend: 2900,
      revenue: 17690,
      roas: 6.10,
      impressions: 57000,
      clicks: 3249,
      ctr: 5.70,
      conversions: 110,
      creative: {
        headline: "Here's 10% Off Your Order 🎁",
        body: "We saved your cart! Use code COMEBACK10 for 10% off. Free delivery included. Offer valid for 48 hours.",
        cta: "Claim My Discount",
        imageUrl: "https://placehold.co/1200x628/27ae60/ffffff?text=Cart+Abandon+10+Off",
      },
    },
    {
      id: "ad_009_1_b",
      adsetId: "as_009_1",
      name: "Cart Abandonment – Urgency Static",
      format: "image",
      spend: 1900,
      revenue: 11110,
      roas: 5.85,
      impressions: 38000,
      clicks: 2071,
      ctr: 5.45,
      conversions: 72,
      creative: {
        headline: "Your Cart Is About to Expire",
        body: "The items in your cart are in high demand. Complete your Samsonite purchase now — stock is limited.",
        cta: "Complete Order",
        imageUrl: "https://placehold.co/1200x628/e67e22/ffffff?text=Cart+Urgency+Ad",
      },
    },
  ],
};

export async function GET(request: NextRequest) {
  const { searchParams } = new URL(request.url);
  const adsetId = searchParams.get("adsetId");

  if (!adsetId) {
    return NextResponse.json({ error: "adsetId query parameter is required" }, { status: 400 });
  }

  const ads = ADS[adsetId];
  if (!ads) {
    return NextResponse.json([]);
  }

  return NextResponse.json(ads);
}
